# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-15 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180315_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='value',
            new_name='size',
        ),
    ]
